name: FTP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: FTP Uploader
        uses: zinh/ftp-uploader-action@v1.0.0
        with:
          ftpHostname: server24.hostonnet.com
          ftpUsername: ${{ secrets.FTP_USERNAME }}
          ftpPassword: ${{ secrets.FTP_PASSWORD }}
          src: .
          dest: /public_html/
          dryRun: false