name: FTP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 51.68.251.120
          port: 21
          username: edudemohon
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: "/public_html/"